### ISSUE TITLE
图标超大，把地址栏都给撑宽了

### ISSUE THREAD

**Issue by Chriser001** [foreverglory/icp-show-webextension#1]
[http://p1.bqimg.com/1949/bc2f98ec919492ec.png](url) 就这样，就这样，就这样，2333

**Comment by foreverglory** [comment]
请提供一下您的浏览器版本及操作系统

**Comment by Chriser001** [comment]
原因已找到，使用默认主题不会变大，我使用的是第三方主题 FT DeepDark ，导致此插件的图表变为巨大，但是其他地址栏上显示图标的插件未变得巨大，FF 50.1 x64   Win10 HOME , theme  FT DeepDark ,我想或许是显示图标过大导致的该主题显示出现这个问题，感谢回访。

**Comment by foreverglory** [comment]
我已经提交修复版本，更新了小图标，等待审核中

**Comment by Chriser001** [comment]
十分感谢

**Comment by Chriser001** [comment]
"page_action": {
        "default_icon": "icons/icon.png",
        "default_title": "查看备案信息",
        "default_popup": "pages/popup.html"
    },
this icon so big.

**Comment by foreverglory** [comment]
看看这个版本是否已经解决了你的问题
[https://addons.mozilla.org/firefox/downloads/file/573001/icp_show-1.0.5-an+fx-windows.xpi?src=devhub](https://addons.mozilla.org/firefox/downloads/file/573001/icp_show-1.0.5-an+fx-windows.xpi?src=devhub)

**Comment by foreverglory** [comment]
安装未签名插件 [https://support.mozilla.org/zh-CN/kb/add-ons-signing-firefox?as=u&utm_source=inproduct#w_dalioucllleeyzgaauoeoeoakekikakneojdeeniko](https://support.mozilla.org/zh-CN/kb/add-ons-signing-firefox?as=u&utm_source=inproduct#w_dalioucllleeyzgaauoeoeoakekikakneojdeeniko)
或者等待审核通过更新版本到1.0.5

**Comment by foreverglory** [comment]
新版本已通过审核 [https://addons.mozilla.org/zh-CN/firefox/addon/icp-show/](https://addons.mozilla.org/zh-CN/firefox/addon/icp-show/)
